### ISSUE TITLE
Freno ID (arduino ID) field in "Add a New Vehicle" modal is NaN

### ISSUE THREAD

**Issue by arshiannafi** [sdevalapurkar/smart-brake-monitor#25]
### Steps

1. Type in something
2. Delete everything

Observe the issue

### Screenshots

![image](https://user-images.githubusercontent.com/19654498/61752169-98e2a780-ad5f-11e9-997e-7083f9e833a6.png)

**Comment by sdevalapurkar** [comment]
is this issue still relevant or has it been resolved? @arshiannafi
